### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by danilNil** [pangratz/ember-cli-htmlbars-inline-precompile#22]
Hello,

I got one problem when I tried to install this package:

```
$ ember install ember-cli-htmlbars-inline-precompile
version: 1.13.1
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/danil/Documents/1_nodejs/Penton/Node-FleetSeek-Ember/node_modules/ember-cli/lib/models/project.js:484:53
    at baseFindIndex (/Users/danil/Documents/1_nodejs/Penton/Node-FleetSeek-Ember/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
    at /Users/danil/Documents/1_nodejs/Penton/Node-FleetSeek-Ember/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
    at Project.findAddonByName (/Users/danil/Documents/1_nodejs/Penton/Node-FleetSeek-Ember/node_modules/ember-cli/lib/models/project.js:483:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/Users/danil/Documents/1_nodejs/Penton/Node-FleetSeek-Ember/node_modules/ember-cli/lib/tasks/addon-install.js:64:30)
    at Class.module.exports.Task.extend.installBlueprint (/Users/danil/Documents/1_nodejs/Penton/Node-FleetSeek-Ember/node_modules/ember-cli/lib/tasks/addon-install.js:53:30)
    at Class.<anonymous> (/Users/danil/Documents/1_nodejs/Penton/Node-FleetSeek-Ember/node_modules/ember-cli/lib/tasks/addon-install.js:43:19)
    at lib$rsvp$$internal$$tryCatch (/Users/danil/Documents/1_nodejs/Penton/Node-FleetSeek-Ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/danil/Documents/1_nodejs/Penton/Node-FleetSeek-Ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/danil/Documents/1_nodejs/Penton/Node-FleetSeek-Ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
```

ember-cli: 1.13.1
node: 0.12.2
npm: 2.12.1

Can someone help me with that?

**Comment by pangratz** [comment]
What version of `ember-cli-htmlbars-inline-precompile` are you using? Any chance you can create a repository with a failing setup?

**Comment by danilNil** [comment]
I've tried to install it with new ember-cli project and it works fine. So I think there is some issue in my code. Thanks!

**Comment by pangratz** [comment]
Alright, thanks for the info. I am closing this issue then. Please feel free to reopen if you encounter this issue again ...
